### PR TITLE
Bug fixes - goerli dev deployments

### PR DESCRIPTION
**Pull request by ryley-o**
This updates two items:
- fix casing on deployment scripts (something updated and now requires lowercase)
- Update top level entity `ProposedArtistAddressesAndSplits` --> `ProposedArtistAddressesAndSplit`
  - don't end in `s` to enable the query for multiples

### CODE REVIEW

**Comment by ryley-o** [comment]
Note that this was deployed to goerli dev to enable a remote schema update sooner rather than later 😅

**Review by jakerockland — APPROVED** [review]

**Comment by ryley-o** [comment]
Also wanted to note that this branch deployed to mainnet studio (as discussed w/ @yoshiwarab)

```
Build completed: QmRpaeVuNZv1qg1MaRfEL4NxVZQsNzDbzkroNNAKVgor1C

Deployed to https://thegraph.com/studio/subgraph/art-blocks

Subgraph endpoints:
Queries (HTTP):     https://api.studio.thegraph.com/query/28238/art-blocks/v0.0.19
```

**Comment by ryley-o** [comment]
Also wanted to note that this branch deployed to mainnet decentralized:
https://github.com/ArtBlocks/artblocks-subgraph/releases/tag/v0.0.19-decentralized

**Comment by ryley-o** [comment]
@lyaunzbe ping as a reminder on this one - should be good to merge

**Review by lyaunzbe — APPROVED** [review]

**Pull request merged**
