### PR TITLE
V3/Minter Suite

### PR DESCRIPTION
**Pull request by ryley-o**
Update V3 core's handlers and tests for the V3-associated minter suite. Also update subgraph template.

The new V3-compatible minters do not emit any different events relative to the latest V1-compatible minters. This PR does a few things:
- Adds new minter contracts to subgraph template, adds their ABIs, etc.
- Generalizes `minter-filter-mapping.ts` to use `IMinterFilterV0` events, where possible, to avoid redundant handlers. Updates handlers to account for new `MinterFilterV1`.
- Updates `minter-suite-mapping.ts` to handle events for the six new minters
  - use common handlers between different minter version handlers where possible, to avoid redundant handlers
- Update minter suite mapping test suite:
  - Refactor/organize existing tests in `describe` blocks
  - In general, have all tests of minter-version-specific events test all applicable minter versions on their specific handlers (vs. only testing generic handler for one minter version, in many cases)
  - achieve coverage of new minter event handlers

## Lessons Learned
It is recommended to place all minter events in minter interfaces in the future. This helps keep subgraph code cleaner when incrementing the version of minters that maintain previous interfaces by allowing the same interface event to be handled, instead of adding a new minter version's event that must be handled. That being said, writing handlers that accept a generic type ~minimize the overhead associated with events not defined in an interface.

## Follow-on
- update `goerli-dev` config with minter addresses once contracts are deployed. (placeholder `0x0` addresses are used)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202817061735220

### CODE REVIEW

**Review by Jbern16 — APPROVED** [review]

**Comment by ryley-o** [comment]
@yoshiwarab - changed you to optional reviewer since Jon has reviewed 🙏

**Comment by ryley-o** [comment]
@lyaunzbe apologies - didn't mean to merge #94 into this branch... Please ignore those (very minimal) changes when reviewing this one.

**Comment by ryley-o** [comment]
@lyaunzbe gentle ping on this one (I know I've been spamming you with PR reviews lately 😅 ) - merging this one will enable new dev subgraph deployment, which will help out with sync server PRs that I'm working on.

**Review by lyaunzbe — APPROVED** [review]

**Comment by lyaunzbe** [comment]
awesome work + appreciate those @dev comments

**Pull request merged**
