### PR TITLE
Refactor v3 core handlers to interfaces

### PR DESCRIPTION
**Pull request by ryley-o**
## Description of the change

Refactor V3 core handlers to use base interface and helper functions where possible.

This is a fast-follow to #195 that refactors handlers to simplify/reduce code.

Note that the changes in https://github.com/ArtBlocks/artblocks-contracts/pull/550 are included here (still on my todo list to have this repo use the npm package instead of manually updating ABIs like I'm doing in this PR)

### CODE REVIEW

**Comment by ryley-o** [comment]
@yoshiwarab - Just a heads-up that I think this is a good starting point for any of the refactoring work you might be implementing this week 👍 might be quite a few merge conflicts if you were to start off of main

**Review by yoshiwarab — APPROVED** [review]
🙌🙌🙌🙌

**Comment by ryley-o** [comment]
gentle ping on this one @jakerockland (this is a good building block for some upcoming minter-related work)

**Review by lyaunzbe — APPROVED** [review]
awesome! so much code slashed 🗡️ 😄 
(apologies for delayed review)

**Pull request merged**
